"""Ask: SSE chat streaming with a deterministic collage planner."""

from __future__ import annotations

import json

from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse

from tenderising.api import collage
from tenderising.chat import agent as chat_agent
from tenderising.mcp.tools import build_registry

router = APIRouter(prefix="/api/ask", tags=["ask"])

_REGISTRY = build_registry()


def _sse(obj: dict) -> str:
    return f"data: {json.dumps(obj, default=str)}\n\n"


def _context_preamble(message: str, context: dict | None) -> str:
    if not context:
        return message
    bids = context.get("bids") or []
    if not bids:
        return message
    total = context.get("total") or len(bids)
    filters = context.get("filters") or {}
    lines = [
        "- {bid_number} · {category} · {department} · closes {end}".format(
            bid_number=b.get("bid_number", ""),
            category=b.get("category_name") or "",
            department=b.get("department") or "",
            end=(b.get("end_date") or "")[:10],
        )
        for b in bids[:50]
    ]
    filter_desc = json.dumps(filters, default=str) if filters else ""
    return (
        f"The user added {total} bids from Discovery as context"
        + (f" matching filters {filter_desc}" if filter_desc else "")
        + ".\nSample of these bids:\n"
        + "\n".join(lines)
        + "\n\nAnswer questions about these bids by calling search_bids with those filters "
        + "(or get_bid_detail for a specific bid). User question: "
        + message
    )


@router.post("/stream")
async def ask_stream(request: Request) -> StreamingResponse:
    try:
        payload = await request.json()
    except Exception:  # noqa: BLE001
        payload = {}
    message = (payload.get("message") or "").strip()
    if not message:
        return StreamingResponse(
            iter([_sse({"type": "error", "message": "message required"})]),
            media_type="text/event-stream",
        )

    context = payload.get("context")
    question = _context_preamble(message, context)
    history = payload.get("history") or []

    def gen():
        if context and context.get("bids"):
            total = context.get("total") or len(context.get("bids", []))
            yield _sse(
                {
                    "type": "ack",
                    "message": f"Using the {total} bids you added from Discovery…",
                }
            )
        interpreted = False
        final_answer = ""
        try:
            for ev in chat_agent.answer_stream(question, _REGISTRY, history=history):
                etype = ev.get("type")
                if etype == "tool":
                    yield _sse({"type": "tool", "name": ev.get("name")})
                    if ev.get("name") == "search_bids" and not interpreted:
                        interpreted = True
                        interp = collage.interpret_query(message, ev.get("arguments") or {})
                        yield _sse({"type": "interpreted", **interp})
                    for widget in collage.plan_widgets(
                        ev.get("name") or "", ev.get("arguments") or {}, ev.get("result")
                    ):
                        yield _sse({"type": "widget", "widget": widget})
                elif etype == "done":
                    final_answer = ev.get("answer", "")
                    yield _sse({"type": "done", "answer": final_answer})
                else:
                    yield _sse(ev)
        except Exception as exc:  # noqa: BLE001 - stream an error event, never crash
            yield _sse({"type": "error", "message": str(exc)})

    return StreamingResponse(
        gen(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@router.post("/hints")
async def ask_hints(request: Request) -> dict:
    """Follow-up suggestions for a finished turn, generated by the current chat model.

    Kept separate from the streaming endpoint so hint generation never delays or
    blocks the answer stream.
    """
    try:
        payload = await request.json()
    except Exception:  # noqa: BLE001
        payload = {}
    message = (payload.get("message") or "").strip()
    if not message:
        return {"hints": []}
    history = payload.get("history") or []
    answer = payload.get("answer") or ""
    try:
        hints = chat_agent.suggest_followups(message, history, answer)
    except Exception:  # noqa: BLE001 - hints are best-effort
        hints = []
    return {"hints": hints}


@router.post("")
async def ask(request: Request) -> dict:
    try:
        payload = await request.json()
    except Exception:  # noqa: BLE001
        payload = {}
    message = (payload.get("message") or "").strip()
    if not message:
        return {"error": "message required"}
    context = payload.get("context")
    question = _context_preamble(message, context)
    history = payload.get("history") or []
    try:
        result = chat_agent.answer(question, _REGISTRY, history=history)
    except Exception as exc:  # noqa: BLE001 - e.g. LLM provider unreachable
        return {"error": str(exc)}
    widgets: list[dict] = []
    for rnd in result.get("tool_rounds", []):
        widgets.extend(
            collage.plan_widgets(
                rnd.get("tool") or "", rnd.get("arguments") or {}, rnd.get("result")
            )
        )
    return {"answer": result.get("answer", ""), "widgets": widgets}
