import type {
  AlertItem,
  BidDetail,
  BidDocument,
  CalendarEventItem,
  DiscoveryContext,
  Facets,
  MeResponse,
  NoteItem,
  PipelineBoard,
  PipelineItemRow,
  Profile,
  SavedTenderItem,
  SavedViewItem,
  SearchParams,
  SearchResult,
  TagItem,
  Widget,
} from '../lib/types'

const BASE = '/api'

async function getJSON<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
  return res.json()
}

async function request<T>(url: string, method: string, body?: object): Promise<T> {
  const res = await fetch(url, {
    method,
    headers: body ? { 'Content-Type': 'application/json' } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
  return res.json()
}

function toQuery(params: object): string {
  const qs = new URLSearchParams()
  for (const [key, value] of Object.entries(params)) {
    if (value === undefined || value === null || value === '') continue
    qs.set(key, String(value))
  }
  const s = qs.toString()
  return s ? `?${s}` : ''
}

export function searchBids(params: SearchParams): Promise<SearchResult> {
  return getJSON<SearchResult>(`${BASE}/search/bids${toQuery(params)}`)
}

export function getFacets(): Promise<Facets> {
  return getJSON<Facets>(`${BASE}/search/facets`)
}

export function getBidDetail(bidNumber: string): Promise<BidDetail> {
  return getJSON<BidDetail>(`${BASE}/bids${toQuery({ bid_number: bidNumber })}`)
}

export function getSummary(): Promise<Record<string, unknown>> {
  return getJSON(`${BASE}/aggregates/summary`)
}

export function exportBidsUrl(params: object): string {
  return `${BASE}/export/bids${toQuery(params)}`
}

export interface AskEvent {
  type: 'thinking' | 'answer' | 'tool' | 'widget' | 'ack' | 'done' | 'error' | 'interpreted'
  delta?: string
  name?: string
  widget?: Widget
  message?: string
  answer?: string
  summary?: string
  chips?: { label: string; prompt: string }[]
}

export async function askStream(
  message: string,
  context: DiscoveryContext | null,
  history: { role: string; content: string }[],
  onEvent: (ev: AskEvent) => void,
): Promise<void> {
  const res = await fetch(`${BASE}/ask/stream`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message, context: context || null, history }),
  })
  if (!res.ok || !res.body) throw new Error(`${res.status} ${res.statusText}`)
  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buf = ''
  for (;;) {
    const { done, value } = await reader.read()
    if (done) break
    buf += decoder.decode(value, { stream: true })
    let idx: number
    while ((idx = buf.indexOf('\n\n')) >= 0) {
      const chunk = buf.slice(0, idx)
      buf = buf.slice(idx + 2)
      for (const line of chunk.split('\n')) {
        if (!line.startsWith('data: ')) continue
        try {
          onEvent(JSON.parse(line.slice(6)) as AskEvent)
        } catch {
          // ignore malformed frames
        }
      }
    }
  }
}

// Follow-up suggestions for a finished turn, generated by the chat model.
export async function askHints(
  message: string,
  history: { role: string; content: string }[],
  answer: string,
): Promise<string[]> {
  const res = await fetch(`${BASE}/ask/hints`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message, history, answer }),
  })
  if (!res.ok) return []
  const data = (await res.json()) as { hints?: string[] }
  return data.hints || []
}

// --- auth -----------------------------------------------------------------
export function getMe(): Promise<MeResponse> {
  return getJSON(`${BASE}/auth/me`)
}

export function logout(): Promise<{ ok: boolean }> {
  return request(`${BASE}/auth/logout`, 'POST')
}

// --- chat history ----------------------------------------------------------
export interface ChatSessionSummary {
  id: string
  title: string | null
  created_at: string
  updated_at: string
}

export interface ChatMessage {
  role: string
  content: string
}

export interface ChatSessionDetail {
  id: string
  title: string | null
  widgets: Widget[]
  messages: ChatMessage[]
}

export function listChatSessions(): Promise<{ items: ChatSessionSummary[] }> {
  return getJSON(`${BASE}/chat/sessions`)
}

export function createChatSession(): Promise<{ id: string }> {
  return request(`${BASE}/chat/sessions`, 'POST')
}

export function getChatSession(id: string): Promise<ChatSessionDetail> {
  return getJSON(`${BASE}/chat/sessions/${id}`)
}

export function appendChatMessage(id: string, role: string, content: string): Promise<{ ok: boolean }> {
  return request(`${BASE}/chat/sessions/${id}/messages`, 'POST', { role, content })
}

export function putChatWidgets(id: string, widgets: Widget[]): Promise<{ ok: boolean }> {
  return request(`${BASE}/chat/sessions/${id}/widgets`, 'PUT', { widgets })
}

export function deleteChatSession(id: string): Promise<{ ok: boolean }> {
  return request(`${BASE}/chat/sessions/${id}`, 'DELETE')
}

// --- saved widgets ----------------------------------------------------------
export interface SavedWidgetItem {
  id: number
  kind: string
  title: string | null
  data: unknown
  session_id: string | null
}

export function listSavedWidgets(): Promise<{ items: SavedWidgetItem[] }> {
  return getJSON(`${BASE}/workspace/widgets`)
}

export function saveWidget(
  kind: string,
  data: unknown,
  title?: string,
  sessionId?: string,
): Promise<SavedWidgetItem> {
  return request(`${BASE}/workspace/widgets`, 'POST', {
    kind,
    data,
    title,
    session_id: sessionId,
  })
}

export function removeSavedWidget(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/widgets/${id}`, 'DELETE')
}

// --- on-demand document fetch ----------------------------------------------
export async function fetchDocuments(
  bidNumber: string,
): Promise<{ fetched: boolean; documents: BidDocument[]; error?: string }> {
  const res = await fetch(`${BASE}/bids/documents/fetch${toQuery({ bid_number: bidNumber })}`, {
    method: 'POST',
  })
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
  return res.json()
}

// --- workspace ------------------------------------------------------------
export function listSavedTenders(): Promise<{ items: SavedTenderItem[] }> {
  return getJSON(`${BASE}/workspace/saved-tenders`)
}

export function saveTender(bidNumber: string, note?: string): Promise<SavedTenderItem> {
  return request(`${BASE}/workspace/saved-tenders`, 'POST', { bid_number: bidNumber, note })
}

export function removeSavedTender(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/saved-tenders/${id}`, 'DELETE')
}

export function listSavedViews(): Promise<{ items: SavedViewItem[] }> {
  return getJSON(`${BASE}/workspace/saved-views`)
}

export function createSavedView(name: string, filters?: object): Promise<SavedViewItem> {
  return request(`${BASE}/workspace/saved-views`, 'POST', { name, filters })
}

export function removeSavedView(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/saved-views/${id}`, 'DELETE')
}

export function listNotes(): Promise<{ items: NoteItem[] }> {
  return getJSON(`${BASE}/workspace/notes`)
}

export function createNote(
  body: string,
  opts?: { title?: string; bidNumber?: string; tags?: string[] },
): Promise<NoteItem> {
  return request(`${BASE}/workspace/notes`, 'POST', {
    body,
    title: opts?.title,
    bid_number: opts?.bidNumber,
    tags: opts?.tags,
  })
}

export function removeNote(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/notes/${id}`, 'DELETE')
}

export function listTags(): Promise<{ items: TagItem[] }> {
  return getJSON(`${BASE}/workspace/tags`)
}

export function listAlerts(): Promise<{ items: AlertItem[] }> {
  return getJSON(`${BASE}/workspace/alerts`)
}

export function createAlert(name: string, filters?: object): Promise<AlertItem> {
  return request(`${BASE}/workspace/alerts`, 'POST', { name, filters })
}

export function removeAlert(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/alerts/${id}`, 'DELETE')
}

export function listPipeline(): Promise<PipelineBoard> {
  return getJSON(`${BASE}/workspace/pipeline`)
}

export function addToPipeline(bidNumber: string, stage?: string): Promise<PipelineItemRow> {
  return request(`${BASE}/workspace/pipeline`, 'POST', { bid_number: bidNumber, stage })
}

export function movePipeline(id: number, stage: string): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/pipeline/${id}`, 'PATCH', { stage })
}

export function removePipeline(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/pipeline/${id}`, 'DELETE')
}

export function listEvents(): Promise<{ items: CalendarEventItem[] }> {
  return getJSON(`${BASE}/workspace/calendar/events`)
}

export function removeEvent(id: number): Promise<{ ok: boolean }> {
  return request(`${BASE}/workspace/calendar/events/${id}`, 'DELETE')
}

export function getProfile(): Promise<Profile> {
  return getJSON(`${BASE}/workspace/profile`)
}
