"""bid poll state

Revision ID: 30f33517c22b
Revises: 44cf617e8354
Create Date: 2026-09-19 00:53:49.120682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f33517c22b'
down_revision: Union[str, Sequence[str], None] = '44cf617e8354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_poll_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('consecutive_no_change', sa.Integer(), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_poll_state_bid_id'), 'bid_poll_state', ['bid_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_poll_state_bid_id'), table_name='bid_poll_state')
    op.drop_table('bid_poll_state')
    # ### end Alembic commands ###
