"""bid first/last seen

Revision ID: 3bcc080fab6d
Revises: 30f33517c22b
Create Date: 2026-09-19 00:55:57.979619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcc080fab6d'
down_revision: Union[str, Sequence[str], None] = '30f33517c22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bids', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'last_seen')
    op.drop_column('bids', 'first_seen')
    # ### end Alembic commands ###
