"""initial schema

Revision ID: 44cf617e8354
Revises: 
Create Date: 2026-09-19 00:49:32.878870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cf617e8354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['buyer_orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_orgs_name'), 'buyer_orgs', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.Column('category_name', sa.String(length=256), nullable=True),
    sa.Column('quadrant', sa.String(length=8), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=True)
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('prior_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('prior_retrieval_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_entity_id'), 'change_events', ['entity_id'], unique=False)
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=256), nullable=True),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('num_seen', sa.Integer(), nullable=False),
    sa.Column('num_new', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload_ref', sa.String(length=256), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_evidence_ref_id'), 'raw_evidence', ['ref_id'], unique=True)
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.String(length=64), nullable=False),
    sa.Column('firm_name', sa.String(length=256), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('oem_capacity', sa.String(length=256), nullable=True),
    sa.Column('reseller_capacity', sa.String(length=256), nullable=True),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('catalogue_ref', sa.String(length=256), nullable=True),
    sa.Column('authorisation_evidence', sa.Text(), nullable=True),
    sa.Column('validity_period', sa.String(length=128), nullable=True),
    sa.Column('verification_state', sa.String(length=64), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_seller_id'), 'sellers', ['seller_id'], unique=True)
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_number', sa.String(length=64), nullable=False),
    sa.Column('b_id', sa.String(length=32), nullable=False),
    sa.Column('parent_b_id', sa.String(length=32), nullable=True),
    sa.Column('parent_bid_number', sa.String(length=64), nullable=True),
    sa.Column('bid_type', sa.String(length=16), nullable=True),
    sa.Column('eval_type', sa.String(length=16), nullable=True),
    sa.Column('status_raw', sa.String(length=16), nullable=True),
    sa.Column('status_normalized', sa.String(length=64), nullable=True),
    sa.Column('status_map_version', sa.String(length=32), nullable=True),
    sa.Column('b_status_raw', sa.String(length=16), nullable=True),
    sa.Column('bid_to_ra', sa.Boolean(), nullable=True),
    sa.Column('ra_to_bid', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('category_name', sa.String(length=256), nullable=True),
    sa.Column('total_quantity', sa.String(length=64), nullable=True),
    sa.Column('is_high_value', sa.Boolean(), nullable=True),
    sa.Column('is_bunch', sa.Boolean(), nullable=True),
    sa.Column('is_custom_item', sa.Boolean(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), nullable=True),
    sa.Column('single_packet', sa.Boolean(), nullable=True),
    sa.Column('global_tendering', sa.Boolean(), nullable=True),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tz_uncertain', sa.Boolean(), nullable=False),
    sa.Column('bid_schedule', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('fingerprint_algo_version', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['buyer_orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_b_id'), 'bids', ['b_id'], unique=True)
    op.create_index(op.f('ix_bids_bid_number'), 'bids', ['bid_number'], unique=True)
    op.create_table('direct_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_orgs.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_orders_order_number'), 'direct_orders', ['order_number'], unique=True)
    op.create_table('bid_corrigenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('corrigendum_no', sa.String(length=32), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('prior_version_ref', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_corrigenda_bid_id'), 'bid_corrigenda', ['bid_id'], unique=False)
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mse_mii_status', sa.String(length=64), nullable=True),
    sa.Column('observed_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participation_bid_id'), 'participation', ['bid_id'], unique=False)
    op.create_index(op.f('ix_participation_seller_id'), 'participation', ['seller_id'], unique=False)
    op.create_table('reverse_auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra_id', sa.String(length=32), nullable=True),
    sa.Column('ra_number', sa.String(length=64), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('start_ref_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('step_decrement', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_extension_count', sa.Integer(), nullable=True),
    sa.Column('status_raw', sa.String(length=64), nullable=True),
    sa.Column('status_normalized', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reverse_auctions_bid_id'), 'reverse_auctions', ['bid_id'], unique=False)
    op.create_index(op.f('ix_reverse_auctions_ra_number'), 'reverse_auctions', ['ra_number'], unique=True)
    op.create_table('seller_capacity_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_capacity_scopes_bid_id'), 'seller_capacity_scopes', ['bid_id'], unique=False)
    op.create_index(op.f('ix_seller_capacity_scopes_seller_id'), 'seller_capacity_scopes', ['seller_id'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('ra_id', sa.Integer(), nullable=True),
    sa.Column('l1_seller_id', sa.Integer(), nullable=True),
    sa.Column('awarded_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('award_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['l1_seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['ra_id'], ['reverse_auctions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_bid_id'), 'awards', ['bid_id'], unique=False)
    op.create_index(op.f('ix_awards_ra_id'), 'awards', ['ra_id'], unique=False)
    op.create_table('bid_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('corrigendum_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('pdf_signature_valid', sa.Boolean(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text_ref', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['corrigendum_id'], ['bid_corrigenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_documents_bid_id'), 'bid_documents', ['bid_id'], unique=False)
    op.create_index(op.f('ix_bid_documents_corrigendum_id'), 'bid_documents', ['corrigendum_id'], unique=False)
    op.create_table('bid_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('consignee', sa.String(length=256), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['bid_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_line_items_document_id'), 'bid_line_items', ['document_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('contract_number', sa.String(length=64), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_orgs.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_award_id'), 'contracts', ['award_id'], unique=False)
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_table('document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.String(length=256), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('extraction_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('retrieval_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disclosure_state', sa.String(length=20), nullable=False),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('raw_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['bid_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_links_document_id'), 'document_links', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_links_document_id'), table_name='document_links')
    op.drop_table('document_links')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_award_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_bid_line_items_document_id'), table_name='bid_line_items')
    op.drop_table('bid_line_items')
    op.drop_index(op.f('ix_bid_documents_corrigendum_id'), table_name='bid_documents')
    op.drop_index(op.f('ix_bid_documents_bid_id'), table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_index(op.f('ix_awards_ra_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_bid_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_seller_capacity_scopes_seller_id'), table_name='seller_capacity_scopes')
    op.drop_index(op.f('ix_seller_capacity_scopes_bid_id'), table_name='seller_capacity_scopes')
    op.drop_table('seller_capacity_scopes')
    op.drop_index(op.f('ix_reverse_auctions_ra_number'), table_name='reverse_auctions')
    op.drop_index(op.f('ix_reverse_auctions_bid_id'), table_name='reverse_auctions')
    op.drop_table('reverse_auctions')
    op.drop_index(op.f('ix_participation_seller_id'), table_name='participation')
    op.drop_index(op.f('ix_participation_bid_id'), table_name='participation')
    op.drop_table('participation')
    op.drop_index(op.f('ix_bid_corrigenda_bid_id'), table_name='bid_corrigenda')
    op.drop_table('bid_corrigenda')
    op.drop_index(op.f('ix_direct_orders_order_number'), table_name='direct_orders')
    op.drop_table('direct_orders')
    op.drop_index(op.f('ix_bids_bid_number'), table_name='bids')
    op.drop_index(op.f('ix_bids_b_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_sellers_seller_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_raw_evidence_ref_id'), table_name='raw_evidence')
    op.drop_table('raw_evidence')
    op.drop_table('collection_runs')
    op.drop_index(op.f('ix_change_events_entity_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_buyer_orgs_name'), table_name='buyer_orgs')
    op.drop_table('buyer_orgs')
    # ### end Alembic commands ###
