"""corrigendum external id

Revision ID: 84690f7aa5db
Revises: 3bcc080fab6d
Create Date: 2026-09-19 03:24:00.283921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84690f7aa5db'
down_revision: Union[str, Sequence[str], None] = '3bcc080fab6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid_corrigenda', sa.Column('external_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bid_corrigenda', 'external_id')
    # ### end Alembic commands ###
